let productList = [
  {
    title: "Örjan",
    description: "Medelålders man",
    price: 99,
    amount: 0,
    id: 0,
  },
  {
    title: "Katt",
    description: "Ink regnbåge",
    price: 89,
    amount: 0,
    id: 1,
  },
  {
    title: "Pigvinpenna",
    description: "Inklusive fingrar",
    price: 200,
    amount: 0,
    id: 2,
  },
  {
    title: "Hårboll",
    description: "Med ögon",
    price: 65,
    amount: 0,
    id: 3,
  },
  {
    title: "Ring",
    description: "Med magiska krafter",
    price: 666,
    amount: 0,
    id: 4,
  },
  {
    title: "Hippster-strumpor",
    description: "Med töntig text",
    price: 200,
    amount: 0,
    id: 5,
  },
  {
    title: "One-piece",
    description: "Snott från barn",
    price: 68,
    amount: 0,
    id: 6,
  },
  {
    title: "Lampa",
    description: "Från SS",
    price: 850,
    amount: 0,
    id: 7,
  },
  {
    title: "Cykelhjälm",
    description: "Ink kakel",
    price: 200,
    amount: 0,
    id: 8,
  },
  {
    title: "Tvåhjuling",
    description: "Puch Dakota",
    price: 3500,
    amount: 0,
    id: 9,
  },
  {
    title: "Läderband",
    description: "För överviktig hårdrockare",
    price: 500,
    amount: 0,
    id: 10,
  },
  {
    title: "Krockodil",
    description: "Av uran",
    price: 199,
    amount: 0,
    id: 11,
  },
  {
    title: "Mask",
    description: "Rymdman",
    price: 196,
    amount: 0,
    id: 12,
  },
  {
    title: "Snökula",
    description: "Med klocka",
    price: 6500,
    amount: 0,
    id: 13,
  },
  {
    title: "Jättestor sedel",
    description: "Ink kille",
    price: 200,
    amount: 0,
    id: 14,
  },
];
export function getProducts() {
    return productList;
  }